# Dockerfile

# https://hub.docker.com/r/duvrod/docker-sonar-scanner/
# https://github.com/duviel/docker-sonar-scanner
FROM duvrod/docker-sonar-scanner

COPY ./sonar-runner.properties /root/sonar-scanner-2.8/conf/sonar-scanner.properties
